apps/attractions/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.views.generic.list_detail import object_list

urlpatterns = patterns('attractions.views',
    url(r'^$', view='area_list', name="area_list"),
    url(r'^tag/(?P<tag>[-\w]+)/area/(?P<featured_area>[-\w]+)/$', view='attractions_for', name='attractions_for'),
    url(r'^tag/(?P<tag>[-\w]+)/$', view='attractions_for', name='attractions_for'),
    url(r'^tag/lang/(?P<lang>[\w]+)/area/(?P<featured_area>[-\w]+)/$', view='tag_search', name='tag_search'),
    url(r'^tag/lang/(?P<lang>[\w]+)/$', view='tag_search', name='tag_search'),
    url(r'^detail/(?P<slug>[-\w]+)/$', view='attr_detail', name='attr_detail'),
    url(r'^hotel/(?P<slug>[-\w]+)/$', view='hotel_detail', name='hotel_detail'),
    url(r'^regions/$', view='area_list', name='area_list'),
    url(r'^regions/(?P<slug>[-\w]+)/$', view='area_detail', name='area_detail'),
    url(r'^attraction/(?P<slug>[-\w]+)/vcard/$', 'vcard', {'model_name': 'Attraction',}, name='attr_vcard'),
    url(r'^hotel/(?P<slug>[-\w]+)/vcard/$', 'vcard', {'model_name': 'Hotel',}, name='hotel_vcard'),
    url(r'^ajax/tag_search/(?P<lang>[\w]+)/$', view='ajax_tag', name='ajax_tag'),
    url(r'^ajax/tag_search/(?P<lang>[\w]+)/(?P<slug>[-\w]+)/$', view='ajax_tag', name='ajax_tag'),
)

third-party/django_multilingual/testproject/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from articles.models import *

admin.autodiscover()

urlpatterns = patterns('',
    (r'^$', 'django.views.generic.list_detail.object_list',
     {'queryset': Category.objects.all(),
      'allow_empty': True}),
    (r'^(?P<object_id>[0-9]+)/$', 'django.views.generic.create_update.update_object',
     {'model': Category,
      'post_save_redirect': '/'}),
    (r'^new/$', 'django.views.generic.create_update.create_object',
     {'model': Category}),

    (r'^admin/(.*)', admin.site.root),
)

urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()

from account.openid_consumer import PinaxConsumer

#handler500 = "pinax.views.server_error"

if settings.ACCOUNT_OPEN_SIGNUP:
    signup_view = "account.views.signup"
else:
    signup_view = "signup_codes.views.signup"

from django.contrib.sitemaps import Sitemap
from attractions.models import Area, Attraction
from tagging.models import Tag


class AreaSitemap(Sitemap):
    #changefreq = "never"
    #priority = 0.5

    def items(self):
        return Area.objects.filter(featured=True)

class TagMap(Sitemap):

    def items(self):
        return Tag.objects.all()

    def location(self, obj):
        return '/attractions/tag/%s/' % obj.name

class TagAndAreaMap(Sitemap):

    def items(self):
        strings = [ t.name for t in Tag.objects.all() ]
        together = []
        for t in strings:
            for a in Area.objects.filter(featured=True):
                together.append('%s|%s' % (t, a.slug))

        return together

    def location(self, obj):
        return '/attractions/tag/%s/area/%s/' % (obj.split('|')[0], obj.split('|')[1])

sitemaps = {'areas': AreaSitemap, 'tags': TagMap, 'tags_and_areas': TagAndAreaMap}

urlpatterns = patterns("",
    url(r"^$", "attractions.views.area_list", name="home"),
    
    url(r"^admin/invite_user/$", "signup_codes.views.admin_invite_user", name="admin_invite_user"),
    url(r"^account/signup/$", signup_view, name="acct_signup"),
    
    (r"^attractions/", include("attractions.urls")),
    (r"^(?P<lang>[-\w].*)/attractions/", include("attractions.urls")),
    (r"^about/", include("about.urls")),
    (r"^account/", include("account.urls")),
    (r"^openid/(.*)", PinaxConsumer()),
    (r"^profiles/", include("basic_profiles.urls")),
    (r"^notices/", include("notification.urls")),
    (r"^announcements/", include("announcements.urls")),
    (r'^i18n/setlang/', 'views.setlang'),
    #(r'^i18n/', include('django.conf.urls.i18n')),
    (r"^admin/", include(admin.site.urls)),
    #(r'^en/sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    #(r'^it/sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    url(r'^feedback-form/$', view='views.feedback_form'),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

if settings.SERVE_MEDIA:
    urlpatterns += patterns("",
            (r'^site_media/', include('staticfiles.urls')),
    )

apps/attractions/forms.py
from django import forms

class TagSearch(forms.Form):
    tag_search = forms.CharField(max_length=16, widget=forms.TextInput(attrs={'class':'location'}),)

apps/attractions/views.py
import urllib

from copy import copy
from django.core.urlresolvers import reverse
from django.views.generic.list_detail import object_list
from django.template import RequestContext
from django.shortcuts import get_object_or_404, render_to_response
from django.utils.translation import ugettext as _
from django.http import HttpResponse

from tagging.models import Tag, TaggedItem, ContentType
from tagging.utils import calculate_cloud
from olwidget.widgets import MapDisplay, InfoMap, InfoMapMulti

from attractions.models import Attraction, Hotel, Area, Headline

from forms import TagSearch

map_options = {
    'popups_outside': True,
    'default_lat': -34.0,
    'default_lon': 18.4,
    'default_zoom': 9,
    'zoom_to_data_extent': True,
    'map_div_style': {'width': '620px', 'height': '360px'},
    'layers': ['osm.mapnik', 'google.streets', 'google.satellite', 'google.hybrid',],
    'overlay_style': {'fill_opacity':0.1, 'stroke_color':'#000000'},
}

detail_map_options = {
    'popups_outside': True,
    #'popup_direction': 'br',
    'zoom_to_data_extent': True,
    'cluster': True,
    'map_div_style': {'width': '620px', 'height': '360px'},
    'layers': ['osm.mapnik', 'google.streets', 'google.satellite', 'google.hybrid',],
    #'overlay_style': {'fill_color': '${fillHandler}'},
    #'overlay_style_context': {
    #    'fillHandler': 'function (feature){ return feature.cluster[0].attributes.fill; }',
    #}
}

tag_map_options = detail_map_options.copy()
tag_map_options.update({
    'zoom_to_data_extent': False,
    'default_zoom': 9,
    'default_lat': -34.0,
    'default_lon': 18.7,
})

breadcrumb_base = [
        (_('Home'), '/'),
        (_('All Attractions'), '/attractions/'),
        # why in the hell reverse has error?
]

def area_style(area, lang=None):
    area_style = {'strokeColor': '#000000', 'fill_opacity': 0.7}
    if area.background:
        area_style.update({'fillColor': area.background,})
    else:
        area_style.update({'fillColor': '#e0ffb8',})
    return area_style

attraction_style = {'fill_color': '#0000ff', 'strokeColor': '#0000ff'}
hotel_style = {'fill_color': '#db4ff2', 'strokeColor': '#db4ff2'}

def area_list(request, lang=None):
    """This is the main list with all the featured areas as polygons"""
    from django.utils.translation import get_language
    breadcrumb = [
            (_('Home'), '/'),
            (_('All Regions'), reverse('area_list')),
    ]
    areas = Area.objects.filter(featured=True)
    all_tags = Tag.objects.cloud_for_model(Attraction)
    olmap = InfoMapMulti({'areas':
        [ [ a.poly_simplify(),
            {'html': a.poly_html(), 'style': area_style(a) } ] for a in areas ]},
        options=map_options
    )
    tag_search = TagSearch()
    headlines = Headline.objects.all()

    return render_to_response('attractions/area_list.html', locals(),
            context_instance = RequestContext(request)
    )

def area_detail(request, slug, lang=None):
    area = get_object_or_404(Area, slug=slug)
    areas = Area.objects.filter(featured=True)
    attractions = area.get_attractions()
    tag_search = TagSearch()
    breadcrumb = [
            (_('Home'), '/'),
            (_('All Regions'), reverse('area_list')),
            ( area.nom, '')
    ]
    content = {}
    content.update({'hotels': [
        [ a.point, {'html': a.point_html(),
                    'style': hotel_style,}
        ] for a in area.hotels_list()
    ]})
    content.update({'attractions': [
        [ a.point, {'html': a.point_html(),
                    'style': attraction_style,
        }] for a in attractions
    ]})
    olmap = InfoMapMulti(
        content,
        options=detail_map_options
    )

    return render_to_response('attractions/area_detail.html', locals(),
            context_instance=RequestContext(request))


def attractions_for(request, tag, featured_area=None, lang=None):
    """Get attractions for the given tag, limit to featured_area if given"""

    tag = get_object_or_404(Tag, name=urllib.unquote(tag))
    all_tags = Tag.objects.cloud_for_model(Attraction)
    related_tags = Tag.objects.related_for_model(tag, Attraction,
            counts=True, counts_all=True)
    areas = Area.objects.filter(featured=True)
    tag_search = TagSearch()

    if featured_area:
        # the scope is for a specific featured area
        area = get_object_or_404(Area, slug=featured_area)
        attractions = TaggedItem.objects.get_by_model(Attraction.objects.filter(point__within=area.poly), tag)
        #attractions = Attraction.objects.filter(point__within = area.poly, tags__contains=tag.name)
        poi = {}
        poi.update({'hotels':
            [ [ a.point, {'html': a.point_html(), 'style': hotel_style} ] for a in area.hotels_list() ]
        })
        # put the attractions on top of the hotels
        poi.update({'attractions':
            [[a.point, {'html': a.point_html(), 'style': attraction_style}] for a in attractions]
        })
        template = 'attractions/area_detail.html'
        breadcrumb = [
            (_('Home'), '/'),
            (_('All'), '/attractions/'),
            (_('Tagged %(tag)s' % {'tag': tag.ml} ),
                reverse('attractions_for', kwargs={'tag': tag.name })),
            (_('Within %s' % featured_area),
                reverse('area_detail', kwargs={'slug': featured_area})),
            (_('Within %(area)s and tagged %(tag)s' % {'area': featured_area, 'tag': tag.name}),
                reverse('area_detail', kwargs={'slug': featured_area})),
        ]
    else:
        hotels = []
        for a in areas:
            hotels.extend(a.hotels_list())
        attractions = TaggedItem.objects.get_by_model(Attraction, tag)
        poi = {}
        # add hotels to the list
        poi.update({'hotels': [
            [h.point, {'html': h.point_html(), 'style': hotel_style}] for h in hotels]
        })
        # add the attractions on top
        poi.update({'attractions':
            [[a.point, {'html': a.point_html(), 'style': attraction_style}] for a in attractions]
        })

        template = 'attractions/area_list.html'
        breadcrumb = [
            (_('Home'), '/'),
            (_('All Attractions'), '/attractions/'),
            (_('Attractions For %(tag)s' % {'tag': tag.ml} ),
                reverse('attractions_for', kwargs={'tag': tag.name }))
        ]

    olmap = InfoMapMulti(
        poi,
        options=tag_map_options
    )
    return render_to_response(template, locals(),
            context_instance = RequestContext(request))

def hotel_list(request, lang=None):
    breadcrumb = [
        (_('Home'), '/'),
        (_('All Hotels'), '/attractions/hotels/'),
    ]
    olmap = InfoMap(
        [ [ a.point, a.point_html() ] for a in Hotel.objects.all() ],
        options=map_options
    )
    tags = []
    return render_to_response('attractions/hotel_list.html', locals(),
            context_instance=RequestContext(request))

def hotel_detail(request, slug, lang=None):
    hotel = get_object_or_404(Hotel, slug=slug)
    breadcrumb = [
        (_('Home'), '/'),
        (_('All Hotels'), '/attractions/hotels/'),
        ( hotel.name, request.path),
    ]

    return render_to_response('attractions/hotel_detail.html', locals(),
            context_instance=RequestContext(request))


def vcard(request, model_name, slug, lang=None):
    """
    Returns a vcard representing the item specified in the arguments
    """
    if model_name == 'Attraction':
        item = get_object_or_404(Attraction, slug=slug)
    elif model_name == 'Hotel':
        item = get_object_or_404(Hotel, slug=slug)
    else:
        return Http404
    response = HttpResponse(mimetype='text/x-vcard')
    response['Content-Disposition'] = 'attachment; filename=%s.vcf'%item.slug
    response.write(item.vcard())
    return response

def ajax_tag(request, lang, slug=None):
    """
    Uses the language code passed in to return a list of matching tags
    """
    search_string = request.GET.get('q', None).lower()
    results = ""
    if search_string:
        if slug:
            area = get_object_or_404(Area, slug=slug)
            if lang.lower() == 'en':
                results = ["%s\n"%t.ml for t in area.tags_list() if search_string in t.ml_en.lower()]
            elif lang.lower() == 'it':
                results = ["%s\n"%t.ml for t in area.tags_list() if search_string in t.ml_it.lower()]
        else:
            if lang.lower() == 'en':
                instances = Tag.objects.filter(ml_en__icontains=search_string)
            elif lang.lower() == 'it':
                instances = Tag.objects.filter(ml_en__icontains=search_string)
            for item in instances:
                results += "%s\n"%item.ml.strip()
    return HttpResponse(results, mimetype='text/plain')

def tag_search(request, lang, featured_area=None):
    """
    Proxy for turning a tag search form POST into the appropriate url
    """
    if request.method == 'POST':
        form = TagSearch(request.POST)
        if form.is_valid():
            search_string = form.cleaned_data['tag_search']
            if lang.lower() == 'en':
                instances = Tag.objects.filter(ml_en__iexact=search_string)
            elif lang.lower() == 'it':
                instances = Tag.objects.filter(ml_en__iexact=search_string)
            if instances.count() == 1:
                tag = instances[0].name
                # good to go
                if featured_area:
                    return attractions_for(request, tag=tag, featured_area=featured_area)
                else:
                    return attractions_for(request, tag=tag)

    if featured_area:
        return area_detail(request, slug=featured_area)
    else:
        return area_list(request)

def attr_detail(request, slug, lang=None):
    attraction = get_object_or_404(Attraction, slug=slug)
    areas = Area.objects.filter(featured=True)

    breadcrumb = [
        (_('Home'), '/'),

apps/attractions/templates/attractions/area_detail.html
{% extends 'attractions/base.html' %}
{% load attraction_tags %}
{% load i18n %}

{% block extra_head %}
{{olmap.media}}
{% endblock %}

{% block body_class %}areas{% endblock %}

{% block subnav %}
<!-- sub nav -->
<ul class="subnav">
    {% for a in areas %}
    <li><a href="{{ a.get_absolute_url }}">{{ a.nom }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

{% block body %}
<div class="content">
    <div class="map_wrapper">
        {{olmap}}
    </div>
        <!-- accordion -->
    {% if area.descriptions.all %}
        {% for description in area.descriptions.all %}
        <h2 class="trigger"><a href="#">{{description.title}}</a></h2>
        <div class="toggle_container">
            <div class="block">
                {{description.content|safe}}
            </div>
        </div>
        <div class="break"></div>
        {% endfor %}
    {% endif %}
    <!-- showreel -->
    {% if area.image %}
    <div class="gallery gallery_wrapper">
        <img src="{{area.image.url}}" width="620" height="260" alt="" />
        <div {% if area.background %}style="background: {{area.background}};"{% endif %}>{{area.headline|safe}}</div>
    </div>
    {% endif %}

</div>
    <!-- sidebar -->
    <div class="sidebar">
    	
        <!-- tabs -->
        <div class="tabs"> 
            <ul class="idTabs"> 
                <li><a href="#idTab1" class="selected">Tags</a></li> 
                {# <li><a href="#idTab2">Hotels</a></li> #}
                <li><a href="#idTab2">Transport</a></li>
            </ul>
            <div id="idTab1" class="rhtab">
                {{ area.render_cloud }}
                {% comment %}
                The fact that this works so poorly is fucking bullshit
                <form action="/attractions/tag/lang/{{LANGUAGE_CODE}}/area/{{area.slug}}/" id="tag_search_form" enctype="multipart/form-data" method="POST">
                    <fieldset>
                        {{tag_search.tag_search}}
                    </fieldset>
                	<fieldset>
                    <input class="search" type="submit" name="search" value=""/> 
                    </fieldset>
                <form>
                {% endcomment %}
            </div>
            {% comment %}
            <div id="idTab2" class="rhtab">
                <form name="search" id="search" action="">
                	<fieldset>
                    	<input class="location" type="text" value="Search Hotels" />
                    </fieldset>
                    <fieldset>
                        <label class="date">Check in date</label>
                        <input name="checkout_date" id="checkout_date" class="date" type="text" value="dd/mm/yyyy" />
                    </fieldset>
                    <fieldset>
                        <label class="date">Check out date</label>
                        <input name="checkin_date" id="checkin_date" class="date" type="text" value="dd/mm/yyyy" />
                    </fieldset>
                    <fieldset>
                    	<input type="checkbox" class="check" />
                        <label class="check">I don't have specific dates</label>
                    </fieldset>
                    <fieldset>
                      	<input class="search" type="submit" name="search" value="" />
                    </fieldset>
                </form>
            </div>
            {% endcomment %}
            <div id="idTab2" class="rhtab">
             {% include 'attractions/transport_div.html' %}
            </div>
        </div>

        <div class="flickr_wrapper">
            <h2>{{ area.name }}</h2>
            <ul class="flickr">
            </ul>
        </div>
        
    </div>
{% endblock %}

apps/attractions/templates/attractions/area_list.html
{% extends 'attractions/base.html' %}
{% load attraction_tags %}
{% load i18n %}

{% block extra_head %}
{{olmap.media}}
{% endblock %}

{% block body_class %}areas{% endblock %}

{% block subnav %}
<!-- sub nav -->
<ul class="subnav">
    {% for a in areas %}
    <li><a href="{{ a.get_absolute_url }}">{{ a.nom }}</a></li>
    {% endfor %}
</ul>
{% endblock %}
{% block above_body %}
<div>
    {% if tag %}<span class="map_legend"><span>{% trans "Map Colour Key:" %}</span> <img src="{{ STATIC_URL }}images/pinkdot.png" alt="pink dot"/> {% trans "= Hotels" %} <img src="{{ STATIC_URL }}images/bluedot.png" alt="blue dot"/>{% trans "= Attractions" %}</span>
    {% endif %}
    {% show_breadcrumb breadcrumb %}
</div>
{% endblock %}


{% block body %}
<div class="content">
    <div class="map_wrapper">
        {{olmap}}
    </div>
    <!-- showreel -->
    <div id="slideshow">
    {% if areas %}
        {% for item in areas %}
            {% if item.image %}
    <div class="gallery gallery_wrapper">
        <img src="{{item.image.url}}" width="620" height="260" alt="" />
        <div {% if item.background %}style="background: {{item.background}}"{% endif %}>{{item.headline|safe}}</div>
    </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    </div>
    <!-- accordion -->
    {% if headlines %}
        {% for headline in headlines %}
            {{ headline.html|safe }}
        {% endfor %}
    {% endif %}
</div>
    <!-- sidebar -->
    <div class="sidebar">
    	
        <!-- tabs -->
        <div class="tabs"> 
            <ul class="idTabs"> 
                <li><a href="#idTab1" class="selected">Tags</a></li> 
                {# <li><a href="#idTab2">Hotels</a></li> #}
                <li><a href="#idTab2">Transport</a></li>
            </ul>
            <div id="idTab1" class="rhtab">
                {% cloud all_tags %}
                {% comment %}
                Not even my bitching is DRY, fucking bullshit I say
                <form action="/attractions/tag/lang/{{LANGUAGE_CODE}}/" id="tag_search_form" enctype="multipart/form-data" method="POST">
                	<fieldset>
                        {{tag_search.tag_search}}
                    </fieldset>
                	<fieldset>
                    <input class="search" type="submit" name="search" value=""/> 
                    </fieldset>
                <form>
                {% endcomment %}
            </div>
            {% comment %}
            <div id="idTab2" class="rhtab">
                <form name="searchhotels" id="searchhotels" class="searchform" action="">
                	<fieldset>
                    	<input class="location" type="text" value="Search Hotels" />
                    </fieldset>
                    <fieldset>
                        <label class="date">Check in date</label>
                        <input name="checkout_date" id="checkout_date" class="date" type="text" value="dd/mm/yyyy" />
                    </fieldset>
                    <fieldset>
                        <label class="date">Check out date</label>
                        <input name="checkin_date" id="checkin_date" class="date" type="text" value="dd/mm/yyyy" />
                    </fieldset>
                    <fieldset>
                    	<input type="checkbox" class="check" />
                        <label class="check">I don't have specific dates</label>
                    </fieldset>
                    <fieldset>
                      	<input class="search" type="submit" name="search" value="" />
                    </fieldset>
                </form>
            </div>
            {% endcomment %}
            <div id="idTab2" class="rhtab">
                {% include 'attractions/transport_div.html' %}
            </div>
        </div>

        <div class="flickr_wrapper">
            <h2>{% trans "Citta' del Capo" %}</h2>
            <ul class="flickr">
            </ul>
        </div>
    </div>
{% endblock %}

apps/attractions/templates/attractions/attraction_list.html
{% extends 'attractions/base.html' %}
{% load tagging_tags %}
{% load i18n %}

{% block extra_head %}
{{olmap.media}}
{% endblock %}

{% block body %}
<!-- content -->
<div class="content">
    {% cloud tags %}
    <!-- interactive maps -->
    {{olmap}}
</div>
{% endblock %}

apps/attractions/templates/attractions/attractions_for.html
{% extends 'attractions/base.html' %}
{% load attraction_tags %}

{% block extra_head %}

{{ olmap.media }}
{% endblock %}

{% block body %}
{% cloud related_tags %}
{{ olmap }}
{% endblock %}

apps/attractions/templates/attractions/base.html
{% extends 'site_base.html' %}
{% load attraction_tags %}
{% load i18n %}

{% block head_title %}
{% for x, y in breadcrumb %}
{% if not forloop.first %}{{x}}{% if not forloop.last %}: {% endif %}{% endif %}
{% endfor %}
{% endblock %}

{% block body_class %}attractions{% endblock %}


{% block above_body %}
<div>
{% block legend %}
    <span class="map_legend"><span>{% trans "Map Colour Key:" %}</span> <img src="{{ STATIC_URL }}images/pinkdot.png" alt="pink dot"/> {% trans "= Hotels" %} <img src="{{ STATIC_URL }}images/bluedot.png" alt="blue dot"/>{% trans "= Attractions" %}</span>
{% endblock %}
    {% show_breadcrumb breadcrumb %}
</div>
{% endblock %}

{% block javascript_includes %}
{% if not area %}
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.cycle.all.2.72.js"></script>
{% endif %}
<script>
    var flickrHandler = function(data){
        // append each photo to a li
        $.each(data.items, function(i, item) {
            i = i++;
            $('<img alt=""/>').attr("src",
            item.media.m).attr("title", item.title).appendTo("ul.flickr").wrap('<li><a href="' + item.media.m + '" rel="group"  title="' + item.title + '"></a></li>');
            // convert to small thumb
            $("ul.flickr li a img").each(function() {
                var smallThumb = $(this).attr("src").replace(/_m.jpg$/i,'_s.jpg'); 
                $(this).attr("src", smallThumb);
            });
            // modify to regular image size
            $("ul.flickr li a").each(function() {
                var modURL = $(this).attr("href").replace(/_m.jpg$/i,'.jpg');
                $(this).attr("href", modURL);
    
                $(this).fancybox({                                                                                                                
                    'titleShow' : true,
                    'titlePostion': 'outside',
                    'cyclic': true,
                    'showNavArrows': true
                });
            });
            if(i==11) return false;    
        });
    }
</script>
{% endblock %}

{% block document_ready %}
{% if area %}
$("#id_tag_search").autocomplete("/attractions/ajax/tag_search/{{LANGUAGE_CODE}}/{{area.slug}}", { minChars: 2}) 
$.getJSON("http://api.flickr.com/services/feeds/groups_pool.gne?id={{area.flickr_group}}&lang=en-us&format=json&jsoncallback=?",
flickrHandler
);
{% else %}
$("#id_tag_search").autocomplete("/attractions/ajax/tag_search/{{LANGUAGE_CODE}}", { minChars: 2}) 
$('#slideshow').cycle({ fx: 'fade', height: '260px',speed: 5000 });
$.getJSON("http://api.flickr.com/services/feeds/groups_pool.gne?id=1340769@N24&lang=en-us&format=json&jsoncallback=?",
flickrHandler
);
{% endif %}
{% endblock %}

apps/attractions/templates/attractions/breadcrumb.html
<!-- breadcrumb -->
{% if nodes %}
    <ul class="breadcrumb">
    {% for x, y in nodes %}
        {% if forloop.last and not forloop.first %}
        <li><span>{{x}}</span></li>
        {% else %}
        <li><a href="{{y}}">{{x}}</a> &raquo;</li>
        {% endif %}
        {% endfor %}
    </ul>
{% endif %}

apps/attractions/templates/attractions/cloud_for_area.html
<ul id="cloud">
{% for t in tags %}
<li class="tag-{{t.font_size}}">
    <a href="{% url attractions_for tag=t.url_name %}"> {{ t.ml}} ({{ t.count }})</a>
</li>
{% endfor %}
</ul>

apps/attractions/templates/attractions/cloud_for_tags.html
<ul id="cloud">
{% for t in tags %}
<li class="tag-{{t.font_size}}">
    {% if areas %}
    <a href="{% url areas_for tag=t.url_name %}"> {{ t.ml}} ({{ t.count }})</a>
    {% else %}
    <a href="{% url attractions_for tag=t.url_name %}"> {{ t.ml}} ({{ t.count }})</a>
    {% endif %}
</li>
{% endfor %}
</ul>

apps/attractions/templates/attractions/detail.html
{% extends 'attractions/base.html' %}
{% load i18n %}

{% block extra_head %}
{{olmap.media}}
{% endblock %}


{% block body %}
<h1>{{attraction}}</h1>
{{attraction.render_cloud}}
<form method='get' action="">
    {% trans "Show Hotels within" %}
    <input id="hotels_within" name="hotels_within"/>
    {% trans 'kilometers' %}
    <input type='submit' value='Go!'/>
    <a href="{{request.path}}">Clear</a>
</form>
{{olmap}}
<h2>{% trans "Related Attractions" %}</h2>
{% for a in attraction.related_attractions %}
<a href="{{a.get_absolute_url}}">{{ a.name }}</a>
{% endfor %}
{% endblock %}

{% block extra_body %}
<script>
    $(function() {
        $('input#hotels_within').val('{{request.GET.hotels_within}}');
    });
</script>
{% endblock %}

apps/attractions/templates/attractions/hotel_detail.html
{% extends 'attractions/base.html' %}
{% load i18n %}

{% block extra_head %}
{{olmap.media}}
{% endblock %}

{% block body_class %}hotels{% endblock %}

{% block body %}
<h1>{{attraction}}</h1>
{{attraction.render_cloud}}
<form method='get' action="">
    {% trans "Show Hotels within" %}
    <input id="hotels_within" name="hotels_within"/>
    {% trans 'kilometers' %}
    <input type='submit' value='Go!'/>
    <a href="{{request.path}}">Clear</a>
</form>
{{olmap}}
<h2>Related Attractions</h2>
{% for a in attraction.related_attractions %}
<a href="{{a.get_absolute_url}}">{{ a.name }}</a>
{% endfor %}
{% endblock %}

{% block extra_body %}
<script>
    $(function() {
        $('input#hotels_within').val('{{request.GET.hotels_within}}');
    });
</script>
{% endblock %}

apps/attractions/templates/attractions/hotel_list.html
{% extends 'attractions/base.html' %}
{% load attraction_tags %}

{% block extra_head %}
{{olmap.media}}
{% endblock %}

{% block body_class %}hotels{% endblock %}

{% block body %}
{% cloud tags %}
{{olmap}}
{% endblock %}